Repository altlinux/admc, pull requests merged in 2020-06, with the labels that each got.

#25 qt5-base package is non-existent; use qt5-base-common
  adtool.spec
Labels: bug

#37 Settings and actions work
  CMakeLists.txt
  src/ad_proxy_model.cpp
  src/admc.cpp
  src/admc.h
  src/create_entry_dialog.cpp
  src/details_widget.cpp
  src/details_widget.h
  src/entry_widget.cpp
  src/entry_widget.h
  src/main_window.cpp
  src/main_window.h
  src/settings.cpp
  src/settings.h
Labels: enhancement

#38 Update dn2domain function
  adldap/CMakeLists.txt
  adldap/active_directory.c
  adldap/cmake/Modules/AddCMockaTest.cmake
  adldap/cmake/Modules/AddMockedTest.cmake
  adldap/test/CMakeLists.txt
  adldap/test/test_adldap.c
  adtool.spec
Labels: enhancement

#43 Update cache
  src/ad_interface.cpp
  src/ad_interface.h
  src/ad_model.cpp
  src/ad_model.h
  src/details_widget.cpp
  src/details_widget.h
  src/members_model.cpp
  src/members_model.h
Labels: admc

#44 Status log
  CMakeLists.txt
  src/main_window.cpp
  src/settings.cpp
  src/settings.h
  src/status.cpp
  src/status.h
  src/status_bar.cpp
Labels: admc

#50 add cli
  src/Runner.cpp
  src/ad_interface.cpp
  src/ad_interface.h
Labels: admc

#45 moving non-leaf entries
  src/ad_interface.cpp
  src/ad_interface.h
  src/ad_model.cpp
  src/ad_model.h
  src/details_widget.cpp
  src/details_widget.h
Labels: admc

#52 Split admodel
  CMakeLists.txt
  src/ad_model.cpp
  src/ad_model.h
  src/attributes_model.cpp
  src/containers_widget.cpp
  src/containers_widget.h
  src/contents_widget.cpp
  src/contents_widget.h
  src/entry_model.cpp
  src/entry_model.h
  src/entry_proxy_model.cpp
  src/entry_proxy_model.h
  src/main_window.cpp
Labels: admc

#42 adldap: Eliminate deprecated functions
  adldap/active_directory.c
Labels: adldap, enhancement
