Repository altlinux/admc, pull requests merged in 2021-06, with the labels that each got.

#209 Debpkg
  .gear/admc.spec
  CMakeLists.txt
  Dockerfile.debian
  debian/changelog
  debian/compat
  debian/control
  debian/copyright
  debian/rules
  doc/CMakeLists.txt
  src/adldap/CMakeLists.txt
  src/adldap/samba/ndr_security.c
  src/admc/CMakeLists.txt
  tests/CMakeLists.txt
Labels: enhancement, feature

#210 Security tab
  .gear/admc.spec
  src/adldap/CMakeLists.txt
  src/adldap/ad_config.cpp
  src/adldap/ad_config.h
  src/adldap/ad_config_p.h
  src/adldap/ad_defines.h
  src/adldap/ad_display.cpp
  src/adldap/ad_display.h
  src/adldap/ad_interface.cpp
  src/adldap/ad_interface.h
  src/adldap/ad_object.cpp
  src/adldap/ad_object.h
  src/adldap/ad_security.cpp
  src/adldap/ad_security.h
  src/adldap/ad_utils.cpp
  src/adldap/ad_utils.h
  src/adldap/samba/dom_sid.c
  src/adldap/samba/dom_sid.h
  src/adldap/samba/gp_manage.c
  src/adldap/samba/gp_manage.cpp
  src/adldap/samba/gp_manage.h
  src/adldap/samba/libsmb_xattr.c
  src/adldap/samba/libsmb_xattr.h
  src/adldap/samba/misc.h
  src/adldap/samba/ndr_misc.c
  src/adldap/samba/ndr_misc.h
  src/adldap/samba/ndr_security.c
  src/adldap/samba/ndr_security.h
  src/adldap/samba/replace.h
  src/adldap/samba/security_descriptor.c
  src/adldap/samba/security_descriptor.h
  src/admc/CMakeLists.txt
  src/admc/console_types/console_object.cpp
  src/admc/create_object_dialog.cpp
  src/admc/edits/account_option_edit.cpp
  src/admc/multi_edits/account_option_multi_edit.cpp
  src/admc/properties_dialog.cpp
  src/admc/tabs/account_tab.cpp
  src/admc/tabs/security_tab.cpp
  src/admc/tabs/security_tab.h
  tests/CMakeLists.txt
  tests/admc_test.cpp
  tests/admc_test.h
  tests/admc_test_ad_interface.cpp
  tests/admc_test_object_menu.cpp
  tests/admc_test_security_tab.cpp
  tests/admc_test_security_tab.h
Labels: feature

#225 Test attributes tab
  .gear/admc.spec
  src/admc/editors/multi_editor.cpp
  src/admc/tabs/attributes_tab.cpp
  tests/CMakeLists.txt
  tests/admc_test_attributes_tab.cpp
  tests/admc_test_attributes_tab.h
Labels: test

#226 Single console model
  src/admc/central_widget.cpp
  src/admc/central_widget.h
  src/admc/console_types/console_object.cpp
  src/admc/console_types/console_object.h
  src/admc/console_types/console_policy.cpp
  src/admc/console_types/console_policy.h
  src/admc/console_types/console_query.cpp
  src/admc/console_types/console_query.h
  src/admc/console_widget/console_widget.cpp
  src/admc/console_widget/console_widget.h
  src/admc/console_widget/console_widget_p.h
  src/admc/console_widget/results_view.cpp
  src/admc/console_widget/results_view.h
  src/admc/console_widget/scope_model.cpp
  src/admc/console_widget/scope_model.h
  src/admc/create_query_folder_dialog.cpp
  src/admc/create_query_item_dialog.cpp
  src/admc/edit_query_folder_dialog.cpp
  src/admc/edit_query_item_dialog.cpp
  src/admc/edit_query_item_dialog.h
  src/admc/find_results.cpp
  src/admc/policy_results_widget.cpp
  src/admc/policy_results_widget.h
  src/admc/rename_policy_dialog.cpp
  src/admc/select_policy_dialog.cpp
  src/admc/utils.cpp
  src/admc/utils.h
Labels: enhancement

#227 Test membership tab
  src/admc/find_widget.cpp
  src/admc/select_object_dialog.cpp
  src/admc/tabs/membership_tab.cpp
  tests/CMakeLists.txt
  tests/admc_test.cpp
  tests/admc_test.h
  tests/admc_test_member_of_tab.cpp
  tests/admc_test_member_of_tab.h
  tests/admc_test_members_tab.cpp
  tests/admc_test_members_tab.h
  tests/admc_test_object_menu.cpp
Labels: test
